# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokeoverflow', '0002_auto_20180316_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='joke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to='jokeoverflow.Joke'),
        ),
    ]
