# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokeoverflow', '0002_auto_20180314_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
