# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokeoverflow', '0003_auto_20180316_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='joke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jokeoverflow.Joke'),
        ),
        migrations.AlterField(
            model_name='joke',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jokes', to=settings.AUTH_USER_MODEL),
        ),
    ]
